
export const arabicAlphabet = [
  { letter: 'ا', name: 'Alif', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'apple' },
  { letter: 'ب', name: 'Ba', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'boat' },
  { letter: 'ت', name: 'Ta', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'tiger' },
  { letter: 'ث', name: 'Tha', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'snake' },
  { letter: 'ج', name: 'Jim', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'camel' },
  { letter: 'ح', name: 'Ha', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'horse' },
  { letter: 'خ', name: 'Kha', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'sheep' },
  { letter: 'د', name: 'Dal', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'duck' },
  { letter: 'ذ', name: 'Dhal', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'corn' },
  { letter: 'ر', name: 'Ra', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'rocket' },
  { letter: 'ز', name: 'Zain', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'zebra' },
  { letter: 'س', name: 'Sin', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'sun' },
  { letter: 'ش', name: 'Shin', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'ship' },
  { letter: 'ص', name: 'Sad', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'falcon' },
  { letter: 'ض', name: 'Dad', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'frog' },
  { letter: 'ط', name: 'Ta', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'table' },
  { letter: 'ظ', name: 'Dha', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'envelope' },
  { letter: 'ع', name: 'Ain', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'eye' },
  { letter: 'غ', name: 'Ghain', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'gazelle' },
  { letter: 'ف', name: 'Fa', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'elephant' },
  { letter: 'ق', name: 'Qaf', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'pen' },
  { letter: 'ك', name: 'Kaf', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'book' },
  { letter: 'ل', name: 'Lam', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'lemon' },
  { letter: 'م', name: 'Mim', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'mosque' },
  { letter: 'ن', name: 'Nun', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'star' },
  { letter: 'ه', name: 'Ha', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'pyramid' },
  { letter: 'و', name: 'Waw', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'flower' },
  { letter: 'ي', name: 'Ya', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'hand' },
];

export const arabicNumbers = [
  { number: '١', name: 'Wahid (1)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'one finger' },
  { number: '٢', name: 'Ithnan (2)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'two hands' },
  { number: '٣', name: 'Thalatha (3)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'three balloons' },
  { number: '٤', name: 'Arba\'a (4)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'four wheels' },
  { number: '٥', name: 'Khamsa (5)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'five stars' },
  { number: '٦', name: 'Sittah (6)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'six eggs' },
  { number: '٧', name: 'Sab\'a (7)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'seven dwarves' },
  { number: '٨', name: 'Thamaniyah (8)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'spider legs' },
  { number: '٩', name: 'Tis\'a (9)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'nine planets' },
  { number: '١٠', name: 'Asharah (10)', imageSrc: 'https://placehold.co/100x100.png', dataAiHint: 'ten fingers' },
];
