
export const arabicAlphabet = [
  { letter: 'ا', name: 'Alif' },
  { letter: 'ب', name: 'Ba' },
  { letter: 'ت', name: 'Ta' },
  { letter: 'ث', name: 'Tha' },
  { letter: 'ج', name: 'Jim' },
  { letter: 'ح', name: 'Ha' },
  { letter: 'خ', name: 'Kha' },
  { letter: 'د', name: 'Dal' },
  { letter: 'ذ', name: 'Dhal' },
  { letter: 'ر', name: 'Ra' },
  { letter: 'ز', name: 'Zain' },
  { letter: 'س', name: 'Sin' },
  { letter: 'ش', name: 'Shin' },
  { letter: 'ص', name: 'Sad' },
  { letter: 'ض', name: 'Dad' },
  { letter: 'ط', name: 'Ta' },
  { letter: 'ظ', name: 'Dha' },
  { letter: 'ع', name: 'Ain' },
  { letter: 'غ', name: 'Ghain' },
  { letter: 'ف', name: 'Fa' },
  { letter: 'ق', name: 'Qaf' },
  { letter: 'ك', name: 'Kaf' },
  { letter: 'ل', name: 'Lam' },
  { letter: 'م', name: 'Mim' },
  { letter: 'ن', name: 'Nun' },
  { letter: 'ه', 'name': 'Ha' },
  { letter: 'و', name: 'Waw' },
  { letter: 'ي', name: 'Ya' },
];

export const arabicNumbers = [
  { number: '١', name: 'Wahid' },
  { number: '٢', name: 'Ithnan' },
  { number: '٣', name: 'Thalatha' },
  { number: '٤', name: 'Arba\'a' },
  { number: '٥', name: 'Khamsa' },
  { number: '٦', name: 'Sittah' },
  { number: '٧', name: 'Sab\'a' },
  { number: '٨', name: 'Thamaniyah' },
  { number: '٩', name: 'Tis\'a' },
  { number: '١٠', name: 'Asharah' },
];
